name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull latest and remove old file from repo
      run: |
        git config pull.rebase false
        git pull
        rm -f FlatPack-Release.zip

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'FlatPack-Release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Push changes to remote with previous commit info
      run: |
        # Get previous commit message and author
        COMMIT_MSG="$(git log -1 --pretty=%B)"
        COMMIT_AUTHOR_NAME="$(git log -1 --pretty=%an)"
        COMMIT_AUTHOR_EMAIL="$(git log -1 --pretty=%ae)"

        # Configure git with previous author
        git config user.name "$COMMIT_AUTHOR_NAME"
        git config user.email "$COMMIT_AUTHOR_EMAIL"

        # Commit using previous message and author
        git add -A
        git commit -m "$COMMIT_MSG" || echo "No changes to commit"
        git push --force
