name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "MrJityh"
        git config --global user.email "MrJityh@gmail.com"
        git config pull.rebase false
        git pull
        rm -f MWPreview-Release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'MWPreview-Release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "New Version Released"
        git push --force
